# Generated by Django 4.2.29 on 2026-03-10 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Captcha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, unique=True, verbose_name='验证码key')),
                ('code', models.CharField(max_length=10, verbose_name='验证码')),
                ('image', models.ImageField(upload_to='captchas/', verbose_name='验证码图片')),
                ('expires_at', models.DateTimeField(verbose_name='过期时间')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '图形验证码',
                'db_table': 'captchas',
            },
        ),
        migrations.CreateModel(
            name='EmailQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_email', models.EmailField(max_length=254, verbose_name='收件人')),
                ('subject', models.CharField(max_length=200, verbose_name='邮件主题')),
                ('content', models.TextField(verbose_name='邮件内容')),
                ('status', models.CharField(choices=[('pending', '待发送'), ('sending', '发送中'), ('sent', '已发送'), ('failed', '发送失败')], default='pending', max_length=10)),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('retry_count', models.IntegerField(default=0, verbose_name='重试次数')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='发送时间')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '邮件队列',
                'verbose_name_plural': '邮件队列',
                'db_table': 'email_queue',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='模板名称')),
                ('type', models.CharField(choices=[('register', '注册成功'), ('verify_email', '邮箱验证'), ('reset_password', '密码重置'), ('admin_reset_password', '管理员重置密码')], max_length=20, verbose_name='模板类型')),
                ('subject', models.CharField(max_length=200, verbose_name='邮件主题')),
                ('content', models.TextField(verbose_name='模板内容')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '邮件模板',
                'verbose_name_plural': '邮件模板',
                'db_table': 'email_templates',
            },
        ),
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='设置键')),
                ('value', models.TextField(verbose_name='设置值')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='说明')),
                ('category', models.CharField(default='general', max_length=50, verbose_name='分类')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '系统设置',
                'verbose_name_plural': '系统设置',
                'db_table': 'system_settings',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='avatars/', verbose_name='头像'),
        ),
        migrations.AddField(
            model_name='user',
            name='email_verification_token',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='user',
            name='is_email_verified',
            field=models.BooleanField(default=False, verbose_name='邮箱已验证'),
        ),
        migrations.AddField(
            model_name='user',
            name='password_reset_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='password_reset_token',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
